### ISSUE TITLE
목업 백엔드 만들기

### ISSUE THREAD

**Issue by scarf005** [Team-Snacks/Snacks#13]
[swaggerhub](https://app.swaggerhub.com/apis/Team-Snacks/Snacks/1.0.0)
- API 명세 호스팅
- 목업 API 제공

하여 swaggerhub를 쓰기로 했습니다

**Comment by scarf005** [comment]
mockend는 기관 계정이 유료네요
fastapi로 빠르게 만들 수 있을지 한 번 확인해보겠습니다

**Comment by scarf005** [comment]
[웹소켓용 스웨거 같은거가 있네요](https://www.asyncapi.com)

**Comment by usanglee** [comment]
[swaggerhub link](https://app.swaggerhub.com/apis/Team-Snacks/test/1.0.0)

**Comment by scarf005** [comment]
URL 인자는 복수인데 태그는 단수 (`auth`, `widget`, `user`)여서 `widgets`, `widget` 두 개의 태그로 나오는 것 같습니다

**Comment by scarf005** [comment]
```sh
❯ curl -X 'GET' 'https://virtserver.swaggerhub.com/Team-Snacks/Snacks/1.0.0/users/1/widgets' -H 'accept: application/json'

[ {
  "uuid" : "string",
  "name" : "string",
  "x" : 0,
  "y" : 0,
  "w" : 0,
  "h" : 0
} ]% 
```
잘 작동하네요
완료로 표시해도 될 것 같습니다
