### ISSUE TITLE
라벨명 정하기

### ISSUE THREAD

**Issue by scarf005** [Team-Snacks/Snacks#20]
## 현재 라벨명
기본값, 영어

## 라벨명 제안
#18 에서 가져옴:

- `버그`
- `기능 추가`
- `코드 개선`
- `문서화`
- `기타`

**Comment by owel-hub** [comment]
라벨명을 한글로 바꾸는거군요. 저는 찬성입니다.

**Comment by scarf005** [comment]
그러면 라벨명 수정하고 닫을까요? 다른 분 의견도 받으면 좋을 것 같습니다!

**Comment by dlwndms0812** [comment]
저도 한글화하면 더 이해하기 쉬울 것 같아서 찬성합니다!

**Comment by owel-hub** [comment]
근데 라벨중에 기타는 어떤건가요?
기타 라벨을 달 이슈는 라벨을 안 다는게 낫지 않나 싶기도 하네요..

**Comment by jyhyun97** [comment]
확인했습니다 바꿔도 좋을 것 같네요

**Comment by jyhyun97** [comment]
실수로 이슈 닫아버렸네요; 다시 열었습니다

**Comment by owel-hub** [comment]
흠..그래도 실수로 라벨 안 단 이슈와 구별하려면  
기타 라벨을 다는것도 괜찮은것 같네요. 저는 찬성입니다.

**Comment by scarf005** [comment]
![image](https://user-images.githubusercontent.com/54838975/199185033-2778aaaf-72ce-4b40-ae5a-135eef1da7cf.png)
이런 식으로 추가했습니다. 기타 라벨은 없어도 될 것 같기는 한데, 혹시 몰라서 우선은 넣어보았습니다.
