### ISSUE TITLE
ERD 초안 작성

### ISSUE THREAD

**Issue by usnaglee** [Team-Snacks/Snacks#25]
### 할 일
1. ERD Cloud에 ERD 작성하기.

**Comment by owel-hub** [comment]
ERD 초안입니다.
@scarf005 youkim님도 ERD Cloud 가입 이메일 알려주시면 초대해드리겠습니다.

<img width="670" alt="Screen Shot 2022-11-04 at 4 22 58 PM" src="https://user-images.githubusercontent.com/40191730/199916081-e7631e63-4e52-4eb6-9bf9-b2052b93a50d.png">

[ERD 링크](https://www.erdcloud.com/d/3i5dRvTEHyvj8ajdq)
