### ISSUE TITLE
API 명세 초안 작성

### ISSUE THREAD

**Issue by jyhyun97** [Team-Snacks/Snacks#26]
### 할 일

- [ ] api 명세 작성

**Comment by owel-hub** [comment]
> **user API 초안입니다. 피드백 부탁드립니다.**

# user

## POST /user
회원가입

#### Request Body

```json
{
    email: "string",
    password: "string"
}
```

#### Response

##### 200 회원가입 성공

##### 400 회원가입 실패

1. 잘못된 값 (null or 빈문자열)
2. email 중복
<br>

## GET /user/login
로그인

#### Request Body

```json
{
    email: "string",
    password: "string"
}
```

#### Response

##### 200 로그인 성공

##### 400 로그인 실패

1. 잘못된 값 (null or 빈문자열)
2. 없는 email
4. password 불일치
<br>

## GET /user/widgets
유저가 사용중인 위젯 정보들 서버로부터 다운로드. (uuid는 jwt토큰 통해 얻어옴)

#### Response

##### 200 성공

```json
[
        {
                "name": "widget1",
                "x": 0,
                "y": 0,
                "w": 1,
                "h": 1,
                "data": {
                        "content": string
                }
        },
        {
                "name": "widget2",
                "x": 0,
                "y": 0,
                "w": 2,
                "h": 2,
                "data": {
                        "content": string
                }
        }
]
```

##### 400 다운로드 실패

1. 잘못된 uuid
<br>

### POST /user/widgets
유저가 사용중인 위젯 정보들 서버로 업로드 (uuid는 jwt토큰 통해 얻어옴)

#### Request Body

```json
[
        {
                "name": "widget1",
                "x": 0,
                "y": 0,
                "w": 1,
                "h": 1,
                "data": {
                        "content": string
                }
        },
        {
                "name": "widget2",
                "x": 0,
                "y": 0,
                "w": 2,
                "h": 2,
                "data": {
                        "content": string
                }
        }
]
```

#### Response

##### 200 업로드 성공

##### 400 업로드 실패
1. 잘못된 uuid

**Comment by dlwndms0812** [comment]
괜찮은 것 같습니다!

**Comment by scarf005** [comment]
저희 로그인 방식 그대로 사용하나요? 토큰 형식으로 바꾸고 서버에서는 저장하지 않는 편이 좋지 않을까요?

**Comment by owel-hub** [comment]
@scarf005
1. 자체 로그인이 있으면 이메일, 휴대폰 번호 인증 등의 기능을 구현해볼 수 있음.
2. 취업 후 현업 업무를 고려하면 자체 로그인 구현해보는것도 좋아보임.
등의 이유로 자체 로그인 할 지 말지 일단 보류중입니다.

**Comment by jyhyun97** [comment]
GET /user/widgets 의 response body에서 `"data": {"content": "json-string"}`부분에서 data로 content를 다시 객체화시킨 이유가 궁금합니다
그냥 `"data":  "json-string"` 하지 않는 이유가 있나요

**Comment by owel-hub** [comment]
그 부분이 프론트에서도 꺼내 쓰기 편하고, 백엔드에서도 그 편이 편할거라고 봤습니다.
스트링으로 주고받으면 프론트 백 둘 다 json형식으로 변환하는 과정이 필요한데
json으로 주고받으면 프론트 백 둘 다 그대로 쓰고, 백엔드에서만 DB에 저장하기 전 json을 스트링으로 감까서 집어넣으면 되겠더라구요.

**Comment by owel-hub** [comment]
@scarf005 
혹시 어떤 의도로 링크를 공유해주신걸까요?

**Comment by scarf005** [comment]
말 그대로 참고용입니다.
- 인증 관련된 부분은  `/auth` 하위에서 진행하는 편이 나을 것 같습니다.
- 이메일/비밀번호 로그인이 성공하면 jwt를 반환하게 해서 다른 oauth2 인증 방식과 통일하는 편이 좋을 것 같습니다.
- 회원가입 부분은 생략 가능할까요? 로그인을 시도하고 DB에 사용자 정보가 없으면 새로 만들어도 될 것 같습니다.

**Comment by dlwndms0812** [comment]
회원가입 부분을 생략하여, 로그인시 db에 사용자 정보가 없으면 새로 만든다는 부분 말씀해주셨는데
만일 사용자가 아이디를 잘 못 쳤을시 바로 회원가입 창으로 넘어가버리는 경우같은 예외처리가 있을 수 있을 것 같습니다.

**Comment by owel-hub** [comment]
@scarf005 
1. 인증 관련된 부분은 /auth 하위에서 진행하는 편이 나을 것 같습니다.
2. 이메일/비밀번호 로그인이 성공하면 jwt를 반환하게 해서 다른 oauth2 인증 방식과 통일하는 편이 좋을 것 같습니다.
3. 회원가입 부분은 생략 가능할까요? 로그인을 시도하고 DB에 사용자 정보가 없으면 새로 만들어도 될 것 같습니다.

넵 1번, 2번 동의합니다.
3번은 논의가 좀 필요할 것 같습니다.

**Comment by owel-hub** [comment]
추가적으로 3번은
기존 다른 서비스들과 다른 방식이라 사용자가 낯설어 할 수 있을 것 같아서
기존 서비스들과 같은 형태로 가는게 좋을 것 같다는 생각입니다. (회원가입 O)

**Comment by owel-hub** [comment]
https://github.com/Team-Snacks/Snacks/wiki/API-%EB%AA%85%EC%84%B8%EC%84%9C
API 명세서 업데이트 했습니다.
