### ISSUE TITLE
위젯 정보 API에 대한 논의

### ISSUE THREAD

**Issue by jyhyun97** [Team-Snacks/Snacks#28]
### 할 일

이렇게 두 의견이 있습니다
의견 1. 위젯에 대한 정보를 GET 요청 한 번으로 처리하기
백에서는 아래와 같이 한 번에 위젯 정보를 포함한 내용을 보내주시고, 프론트에서는 아마 부모 컴포넌트에서 이 정보를 받아 자식 컴포넌트(위젯)에 props으로 넘기게 구현하지 않을까 싶습니다.
ex) GET /main
```
{
	[
		{
			위젯명 :  메모,
			위치 및 크기 : {x, y, w, d},
			위젯 데이터 : {메모 내용}
		},
		{
			위젯명 :  날씨,
			위치 및 크기 : {x, y, w, d},
			위젯 데이터 : {지역, 기온 등}
		},
	]
}
```
의견 2. 위젯에 대한 정보를 각각 독립적인 요청으로 처리하기.
백에서는 각 위젯에 대한 테이블을 구축해야 하고 각 요청에 대한 api를 만들고, 프론트에서는 위젯 컴포넌트에서 필요한 정보를 요청하게 될 것 같습니다.
ex) GET /widget/memo
```
{
	위젯명 : 메모
	위치 및 크기 : {x, y, w, d}
	메모 내용 : string
}

```

일단 프론트에서 1번은 각 위젯마다 요청 안만들어도 되지만 자식 컴포넌트의 독립성이 떨어질 것 같고, 2번은 위젯을 독립적으로 만들 수 있는 점이 좋을 것 같습니다

(백엔드 입장에서 장/단점도 설명해주시면 좋겠습니다)

**Comment by scarf005** [comment]
> 위젯에 대한 정보를 GET 요청 한 번으로 처리하기

우선은 첫 번째 방법으로 구현하는 것이 좋을 것 같습니다. 두 번째 방법은 위젯명을 알아야 하기 때문에 첫 번째 방법에 의존성이 있는 것 같습니다.

`/v1/user/:uuid/panel`
- `v1` - api 버전
- `user` - 사용자 자료
- `:uuid` - 사용자 구분자
-  `panel` - 패널 정보

**Comment by owel-hub** [comment]
처음에 로그인 했을때는 1번처럼 전체 위젯 데이터가 필요할 것 같은데

그 이후로는 2번 형태가 되지 않을까 싶습니다.
근데 또 위젯마다 데이터 업데이트 주기와 방법이 다를 것 같아서 로그인 이후로 어떻게 처리할지는 아직 잘 모르겠네요.
1. 날씨앱: 10초마다 기상청 API서버와 통신하여 날씨 데이터 업데이트.
2. 메모앱: (어떤 방식으로 할 지 정해야겠지만 만약 실시간으로 한다면) 타이핑 이벤트 발생할때마다 서버에게 데이터 송신 + 다른 디바이스에서는 수신.

**Comment by dlwndms0812** [comment]
백엔드의 입장에서는 위젯 데이터를 json으로 한번에 묶어서 받고, 보내는 쪽이 좋습니다. 
만일 위젯 별로 필요한 데이터를 보낸다면 해당 위젯의 api, 그리고 데이테베이스의 테이블도 각각 만들어야 하는 문제가 있습니다.
ex) 메모 위젯 GET /widget/memo   -> memo_widget 테이블 생성
      투두리스트 위젯 GET /widget/todo -> todolist_widget 테이블 생성
위젯이 10개가 있다면 위젯 관련 api도 10개 이상, 테이블도 10개 이상이 필요하기 때문입니다.

하지만 한번에 위젯 데이터를 json으로 받는다면, 위젯별로 api를 설계 그리고 데이터베이스 테이블도 설계를 할 필요가 없이 한 번에 처리가 가능하다는 장점이 있습니다.

**Comment by jyhyun97** [comment]
그럼 일단 1번으로 진행하는 걸로 이슈 닫겠습니다~
