### ISSUE TITLE
위젯 정하기

### ISSUE THREAD

**Issue by jyhyun97** [Team-Snacks/Snacks#29]
### 할 일

- [ ] 정리된 위젯 아이디어에서 어떤 위젯을 몇 개 할 것인지 정하기

### 위젯 아이디어 
1. 날씨, 미세먼지
2. 메모장, todo list
3. 아스키코드표, 연산자 우선순위표
4. 단축키 정리 (vim, vscode 등)
5. github잔디 상태
6. 타이머, 스톱워치
7. 북마크
8. 주가,환율
9. 사다리
10. 달력
11. 뽀모도로
12. 축구

**Comment by scarf005** [comment]
3,4 번이 가장 구현하기 쉬우니 먼저 하는것이 어떨까요?

**Comment by dlwndms0812** [comment]
구현할 위젯 순서와 일정을 잡아서 마일스톤 파도 좋을 것 같습니다!

**Comment by jyhyun97** [comment]
1, 2, 3, 7 어떨까요 그래도 출시하려면 위젯이 4종류 정도는 있어야 할 것 같아요

**Comment by owel-hub** [comment]
1(날씨), 2(메모장), 3(아스키코드), 6(타이머), 7(북마크) 요렇게 성격이 다른 5개를 먼저 해보면 좋을 것 같습니다.

**Comment by jyhyun97** [comment]
@scarf005 
오늘 아침 회의했을 때 1, 2, 3, 6, 7 다섯 개 구현하기로 이야기했는데 의견 있으면 남겨주세요!

**Comment by scarf005** [comment]
3번의 연산자 우선순위표는 C 언어를 말하시는 거죠?
모두 괜찮은 것 같습니다

**Comment by jyhyun97** [comment]
> 3번의 연산자 우선순위표는 C 언어를 말하시는 거죠? 모두 괜찮은 것 같습니다

일단은 아스키 코드 표만 구현할 것 같습니다! 1번도 날씨만 구현하고요
