### ISSUE TITLE
백엔드 Code 컨벤션 설정하기

### ISSUE THREAD

**Issue by usanglee** [Team-Snacks/Snacks#30]
### 할 일

1. Intellij Code Style 컨벤션 동일하게 설정하기.
2. 변수, 함수 작명 규칙 등 세우기.

**Comment by usnaglee** [comment]
[Google java styleguide](https://google.github.io/styleguide/javaguide.html)
[Google java styleguide intellij 설정용 xml파일 다운로드](https://github.com/google/styleguide)
