### ISSUE TITLE
도메인 주소 정하기

### ISSUE THREAD

**Issue by scarf005** [Team-Snacks/Snacks#31]
### 할 일

- 서비스 호스팅에 사용할 도메인이 필요합니다
- snacks 계열은 대부분 선점되어있어 확장자 (`.com` 등) 를 정할때 신중해야 합니다

**Comment by scarf005** [comment]
![image](https://user-images.githubusercontent.com/54838975/200466642-56b75985-b748-42a8-9b20-45bff7b5e1f5.png)
가비아에서 1년 13500원으로 제공하는것 같습니다

**Comment by dlwndms0812** [comment]
snacks.kr이 가장 무난한 도메인 이름 같고 가격도 괜찮은것 같네요!
