### ISSUE TITLE
컴포넌트 구조 설계 및 디자인

### ISSUE THREAD

**Issue by jyhyun97** [Team-Snacks/Snacks#32]
### 상세 설명

- [x] 컴포넌트 구조 만들기
- [x] figma 컴포넌트 구조나눠 그룹화 및 이름 지정하기

### 프로세스

-

**Comment by scarf005** [comment]
[아토믹 디자인](https://bradfrost.com/blog/post/atomic-web-design/)을 적용해보면 어떨까요? 사용 후기로는
- [카카오 프론트엔드 기술블로그](https://fe-developers.kakaoent.com/2022/220505-how-page-part-use-atomic-design-system/)
- [velog](https://velog.io/@thsoon/쓸때없이-고퀄인-투두리스트-만들기-FE-2.-뷰-설계)
등이 있습니다
