### ISSUE TITLE
그리드 레이아웃 라이브러리 찾기

### ISSUE THREAD

**Issue by scarf005** [Team-Snacks/Snacks#33]
### 상세 설명

[메트로 UI 스타일](https://en.wikipedia.org/wiki/Metro_(design_language))을 지원하는 리액트 UI 라이브러리 찾기

### 프로세스

- [dnd-kit](https://dndkit.com/)
- [muuri](https://paol-imi.github.io/muuri-react/): 20년 이후 업데이트 없음

**Comment by jyhyun97** [comment]
일단 알고리즘 만들어서 적용시키는 것으로 해보고,, 라이브러리를 뜯어고치거나 새로 만들거나 합시다

**Comment by jyhyun97** [comment]
대체할 라이브러리를 찾지 못하였기에 일단 dnd-kit를 사용하는 것으로 하고 닫겠습니다
