### ISSUE TITLE
Spring Boot 초기 환경 설정

### ISSUE THREAD

**Issue by usanglee** [Team-Snacks/Snacks#36]
### 상세 설명

백엔드 개발을 위한
Spring Boot 초기 환경 설정을 할 예정입니다.

### 프로세스

- Spring Boot Initializer 이용하여 프로젝트 파일 생성.
- Git Repo에 Commit + Push.
- Pull request + Merge.

**Comment by scarf005** [comment]
- [ ] [javadoc](https://breakcoding.tistory.com/385) 지원도 되면 좋을 것 같습니다
