### ISSUE TITLE
프론트엔드 프로젝트 생성

### ISSUE THREAD

**Issue by jyhyun97** [Team-Snacks/Snacks#40]
### 상세 설명

빌드 : vite
언어 : typescript
프레임워크 : react
라이브러리 : dnd kit, mantine, storybook, jotai, socket.io

### 프로세스

-

**Comment by scarf005** [comment]
[react query](https://tanstack.com/query/v4/?from=reactQueryV3&original=https://react-query-v3.tanstack.com/) 또는 [swr](https://swr.vercel.app)

**Comment by jyhyun97** [comment]
@scarf005 얘네도 jotai같은 상태관리 라이브러리인가요

**Comment by scarf005** [comment]
네, 정확히는 http 쿼리 상태관리입니다

**Comment by scarf005** [comment]
jotai와 잘 어울리는 것으로 고르면 될 것 같습니다
우선 react query의 경우에는 jotai에 [연동 가이드](https://jotai.org/docs/integrations/query)가 있기는 하네요

**Comment by scarf005** [comment]
더 읽어볼만한 글:
- https://github.com/pmndrs/jotai/issues/234
- https://velog.io/@soryeongk/ReactSWRTutorial
- https://velog.io/@soryeongk/SWRBasic
