### ISSUE TITLE
일정관리 Notion으로 이사가기 건의

### ISSUE THREAD

**Issue by usanglee** [Team-Snacks/Snacks#49]
일정관리를 노션으로 옮기고 싶다고 말씀드렸었는데 왜 그런지 이야기 드리려 합니다.

1. 일정관리나 문서 공유 시 더 편리해질 것 같아서
2. 포폴로 제출 시  이점이 있을 것 같아서.
입니다.

현재 github를 이용하여 일정관리를 하는 방식이 동선 낭비가 심하다고 느꼈고
이를 해결한다면 더 편해지고 포폴 제출에도 유리하다고 판단했습니다.
아래는 그 이유들입니다.

## 1. 마일스톤 보기가 불편하다.

마일스톤은 프로젝트의 큰 작업 단위입니다.
마일스톤에 대한 정보를 보려면

1. 이슈 탭 들어가기
2. 마일스톤 탭 들어가기
3. 마일스톤 눌러서 할당된 태스크들 보기

3 단계를 거쳐야 합니다.

## 2. 작업 현황(projects 탭) 보기가 불편하다.

할 일이 있어서 이슈 발행을 한 후
다른사람들은 어떤 작업을 하고 있나 보고 싶을 때가 있는데
작업 현황을 보려면 

1. 프로젝트 탭 누르기
2. 본 프로젝트 일정 관리 누르기

2단계를 거쳐야 합니다.

## 3. 캘린더 기능이 없다.

캘린더 기능을 이용하면 우리가 그동안 어떤 활동이나 개발을 했는지 
흐름을 한눈에 직관적으로 파악할 수 있고
나에게 필요한 정보가 어디 있는지 손쉽게 파악할 수 있는데
(리스트 형태보다 달력 형태로 데이터가 나열되어 있는 것이 날짜 간의 전후 관계가 파악되어
필요한 정보를 추리는데 더 편했습니다.)
깃허브에는 캘린더 기능이 없는 게 아쉬었습니다.

## 4. 일정관리와 문서 저장소가 분리됨
github wiki는 에디터 기능이 비루합니다.
그리고 글 수정을 하고 싶다면

1. 편집모드 들어가기
2. 편집하기
3. 수정 완료 버튼 누르기

3 단계를 거쳐야 하지만
노션은 그냥 클릭 후 수정하면 끝입니다.
그렇기에 문서관리는 노션으로 운영하는 것이 좋다고 생각되는데

문서 저장소를 노션으로 운영하고 일정관리는 github에서 운영한다면
github에서 일정관리 중 보고 싶은 문서가 있을때 
노션으로 이동해서 봐야 하지만
일정관리도 노션에서 한다면 한 화면에서 같이 관리할 수 있습니다.

## 5. 커스터 마이징이 불편함
github는 일정관리 or 문서 관리에서 필요한 기능이
노션에비해 굉장히 제한적입니다.
노션은 많은 기능들이 있어 추후 필요한 기능이 있다면
커스터마이징으로 이를 해결하기 좋습니다.

## 6. 서비스 후 일정관리, 문서 저장소를 일반 사용자들에게 노출할 필요가 없음.

일반 사용자들에게는 서비스나 코드 관련된 부분만 노출하면 된다고 봤습니다.
보안상, 프라이버시 상의 이유로 우리의 활동과 일정, 문서들을 노출하고 싶지는 않고
구직 시 인사담당자들에게만 노출하고 싶었는데
일정관리와 문서관리를 노션에서 하면 이를 달성할 수 있었습니다.

위 6가지 부분에서 불편함을 느꼈고
이를 해결하기 위해 노션 사용을 건의드렸습니다.

물론 마일스톤, 일정관리, 문서 저장소를 브라우저의 다른 탭으로 열어놓으면 문제가 해결되겠지만
노션을 쓴다면 굳이 그러지 않아도 되고
Snacks가 사용자들의 탭을 줄이기 위한 대시보드인 만큼 서비스의 철학과도 맞다는 생각이 듭니다.

일정관리와 문서관리를 통합해서 저희에게 불편함이 감소한다면 인사담당자에게도 마찬가지일것이고
포트폴리오 점검 시 인사담당자의 불편함이 준다면 저희의 포폴을 더 긍적적으로 평가될거라 생각합니다.

걱정되는 점, 궁금한 점이 있다면 이슈 댓글이나
내일 회의때 질문 부탁드립니다.

**Comment by usanglee** [comment]
[노션 예시 링크](https://usanglee.notion.site/Snacks-e1f75cd4123040468868fa370a5369f8)

**Comment by scarf005** [comment]
올려주신 내용 잘 읽어 보았습니다. 돌아와서 읽어 보니 확실히 기존 깃허브 프로젝트 보드를 사용할 때보다 나은 점들이 눈에 보이네요.
[깃허브 연동](https://www.notion.so/integrations/github-cdc46cd9-f0e9-48fd-b3aa-18481098e29e)을 사용한다면 PR과 이슈를 달 수 있으니 노션으로 바꾸어도 문제 없을 것 같습니다. 자세한 사항은 내일 다시 만나서 확인해보는 시간을 가지면 좋을 것 같습니다.

**Comment by scarf005** [comment]
https://marketplace.atlassian.com/apps/1221288/external-share-for-jira-lite?hosting=cloud&tab=overview

**Comment by scarf005** [comment]
노션으로 이주하기로 결정되었으므로 닫도록 하겠습니다.
